// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFss96hbUSOFd7voS1vtln6jTy7Q7fBk8',
    appId: '1:829950829288:web:9e717eb6bb3f0693bddf5d',
    messagingSenderId: '829950829288',
    projectId: 'safespace-dd683',
    authDomain: 'safespace-dd683.firebaseapp.com',
    storageBucket: 'safespace-dd683.firebasestorage.app',
    measurementId: 'G-ZVX12KXGGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAk3My9U5bfB1YK1WPP11b_uQMoiwwFhs',
    appId: '1:829950829288:android:439619502a9a8b83bddf5d',
    messagingSenderId: '829950829288',
    projectId: 'safespace-dd683',
    storageBucket: 'safespace-dd683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKj9ohrcszXMpU_UWR9g-lLV7C3e0HOk',
    appId: '1:829950829288:ios:4533637e0ebe94bfbddf5d',
    messagingSenderId: '829950829288',
    projectId: 'safespace-dd683',
    storageBucket: 'safespace-dd683.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyKj9ohrcszXMpU_UWR9g-lLV7C3e0HOk',
    appId: '1:829950829288:ios:4533637e0ebe94bfbddf5d',
    messagingSenderId: '829950829288',
    projectId: 'safespace-dd683',
    storageBucket: 'safespace-dd683.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFss96hbUSOFd7voS1vtln6jTy7Q7fBk8',
    appId: '1:829950829288:web:d2b1ce2b6c014ea4bddf5d',
    messagingSenderId: '829950829288',
    projectId: 'safespace-dd683',
    authDomain: 'safespace-dd683.firebaseapp.com',
    storageBucket: 'safespace-dd683.firebasestorage.app',
    measurementId: 'G-CE1STLP5KW',
  );
}
